In [2]:
import numpy as np

In [3]:
#Lista ou tupla

lista = [1,2,3,4,5]
tupla = (1,2,3,4,5) 

array_lista = np.array(lista)
print(array_lista)    
print(type(array_lista))  

array_tupla = np.array(tupla)
print(array_tupla)    
print(type(array_tupla))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#Usando range

array_simples = np.arange(18)
array_sequencial = np.arange(10, 100, 10)

print("Array simples: ", array_simples)
print("Array sequencial: ", array_sequencial)

Array simples:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Array sequencial:  [10 20 30 40 50 60 70 80 90]


In [9]:
#Criando arrays de zeros, uns e vazios

array_zeros = np.zeros((5))
print("Array de zeros: \n", array_zeros)

array_uns = np.ones((5), dtype=np.int16)
print("Array de uns: \n", array_uns)

array_vazio = np.empty((5))
print("Array vazio: \n", array_vazio)

Array de zeros: 
 [0. 0. 0. 0. 0.]
Array de uns: 
 [1 1 1 1 1]
Array vazio: 
 [0. 0. 0. 0. 0.]


In [ ]:
#Gerando números aleatórios

vetor_aleatorio = np.random.random((5))
print("Vetor aleatório: \n", vetor_aleatorio)

matriz_aleatoria = np.random.random((3,3))
print("Matriz aleatória: \n", matriz_aleatoria)



Vetor aleatório: 
 [0.49830327 0.92924465 0.24884648 0.7428334  0.63471844]
Matriz aleatória: 
 [[0.48105158 0.85134056 0.40014751]
 [0.67423576 0.86877656 0.24027459]
 [0.44218526 0.41687325 0.705706  ]]
Vetor com números inteiros aleatórios: 
 [ 8 14  5  9]


In [17]:
vetor = np.random.randint(low=5, high=15, size=4)
print("Vetor com números inteiros aleatórios: \n", vetor)

Vetor com números inteiros aleatórios: 
 [ 9  6 10 13]


In [18]:
vetor = np.random.uniform(low=5, high=15, size=4)
print("Vetor com números uniforme: \n", vetor)

Vetor com números uniforme: 
 [12.66669302 10.03623037  9.58472243  5.03595534]


In [19]:
#Criando array com mais de uma dimensão
array_2d = np.array([[1,2,3],[4,5,6]])
print("Array 2D: \n", array_2d)
print("Dimensões do array: ", array_2d.shape)
print("Número de dimensões: ", array_2d.ndim)
print("Tipo de dados: ", array_2d.dtype)
print("Tamanho de cada elemento em bytes: ", array_2d.itemsize)
print("Número total de elementos: ", array_2d.size)
print("Tipo do objeto: ", type(array_2d))

Array 2D: 
 [[1 2 3]
 [4 5 6]]
Dimensões do array:  (2, 3)
Número de dimensões:  2
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  6
Tipo do objeto:  <class 'numpy.ndarray'>


In [28]:
lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = [7,8,9]

array_3d = np.array([lista1, lista2, lista3])
print("Array 3D: \n", array_3d)
print("Dimensões do array: ", array_3d.shape)
print("Número de dimensões: ", array_3d.ndim)
print("Tipo de dados: ", array_3d.dtype)
print("Tamanho de cada elemento em bytes: ", array_3d.itemsize)
print("Número total de elementos: ", array_3d.size)
print("Tipo do objeto: ", type(array_3d))

array_2d = np.array([lista1, lista2])
print("Array 2D: \n", array_2d)
print("Dimensões do array: ", array_2d.shape)
print("Número de dimensões: ", array_2d.ndim)
print("Tipo de dados: ", array_2d.dtype)
print("Tamanho de cada elemento em bytes: ", array_2d.itemsize)
print("Número total de elementos: ", array_2d.size)
print("Tipo do objeto: ", type(array_2d))



Array 3D: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensões do array:  (3, 3)
Número de dimensões:  2
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  9
Tipo do objeto:  <class 'numpy.ndarray'>
Array 2D: 
 [[1 2 3]
 [4 5 6]]
Dimensões do array:  (2, 3)
Número de dimensões:  2
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  6
Tipo do objeto:  <class 'numpy.ndarray'>


In [22]:
#Criando matrizes

lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = [7,8,9]

matriz = np.matrix([lista1, lista2, lista3])
print("Matriz: \n", matriz)
print("Dimensões da matriz: ", matriz.shape)
print("Número de dimensões: ", matriz.ndim)
print("Tipo de dados: ", matriz.dtype)
print("Tamanho de cada elemento em bytes: ", matriz.itemsize)
print("Número total de elementos: ", matriz.size)
print("Tipo do objeto: ", type(matriz))



Matriz: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimensões da matriz:  (3, 3)
Número de dimensões:  2
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  9
Tipo do objeto:  <class 'numpy.matrix'>


In [26]:
#Soma de listas e arrays

lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = lista1 + lista2
print("Soma de listas: ", lista3)
array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = array1 + array2
print("Soma de arrays: ", array3)
#Subtração de listas e arrays
lista1 = [1,2,3]
lista2 = [4,5,6]
lista3 = [a - b for a, b in zip(lista1, lista2)]
print("Subtração de listas: ", lista3)
array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = array1 - array2
print("Subtração de arrays: ", array3)

Soma de listas:  [1, 2, 3, 4, 5, 6]
Soma de arrays:  [5 7 9]
Subtração de listas:  [-3, -3, -3]
Subtração de arrays:  [-3 -3 -3]


In [31]:
import timeit

tempo_listas = timeit.timeit('''x = range(1000); y = range(1000); [x[i] + y[i] for i in range(len(x))]''', number=100000)

tempo_vetores = timeit.timeit('''x = np.arange(1000); y = np.arange(1000); x + y''', number=100000,
                              setup='import numpy as np')

print("Tempo de execução com vetores: ", tempo_vetores)
print("Tempo de execução com listas: ", tempo_listas)

print(f'Os vetores foram {tempo_listas/tempo_vetores:.2f} vezes mais rápidos que as listas.')

Tempo de execução com vetores:  0.15613901300821453
Tempo de execução com listas:  7.318184805975761
Os vetores foram 46.87 vezes mais rápidos que as listas.


In [56]:
#Desafio 

acao1 = float(input('Digite a cotação da primeira empresa: '))
acao2 = float(input('Digite a cotação da segunda empresa: '))
acao3 = float(input('Digite a cotação da terceira empresa: '))


carteira = np.array([acao1, acao2, acao3])
print(carteira)

[1. 2. 3.]


In [ ]:
#Desafio 2

n1 = float(input('Digite o primeiro número: '))
n2 = float(input('Digite o segundo número: '))


array_sequencial = np.arange(n1, n2+1) 

print(array_sequencial)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


In [63]:
#desafio 3

import numpy as np
import math

# Sorteio dos números (6 números únicos de 1 a 60)
lista_numeros = np.random.choice(range(1, 61), size=6, replace=False)

print("Números da Mega Sena: ", sorted(map(int, lista_numeros)))


# Probabilidade de ganhar na Mega-Sena (1 / combinações possíveis)
total_combinacoes = math.comb(60, 6)
probabilidade = 1 / total_combinacoes

print("Probabilidade de ganhar na Mega Sena: ", probabilidade)


Números da Mega Sena:  [8, 9, 15, 30, 39, 58]
Probabilidade de ganhar na Mega Sena:  1.997448858318156e-08


# Métodos e atributos

In [ ]:
#Métodos são funções que mudam o estado do objeto ou realizam alguma operação com ele. 
#Exemplo de metodo: set(), sort(), append(), pop(), etc.

#Atributos são propriedades do objeto que fornecem informações sobre ele.
#Exemplo de atributo: shape, ndim, dtype, size, etc.


In [69]:
#Atributos

array = np.arange(10)

print("O array é: ", array)
print("Número de bites do array: ", array.nbytes)
print("Dimensões do array: ", array.shape)
print("Número de dimensões: ", array.ndim)
print("Tipo de dados: ", array.dtype)
print("Tamanho de cada elemento em bytes: ", array.itemsize)
print("Número total de elementos: ", array.size)
print("Tipo do objeto: ", type(array))  

O array é:  [0 1 2 3 4 5 6 7 8 9]
Número de bites do array:  80
Dimensões do array:  (10,)
Número de dimensões:  1
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  10
Tipo do objeto:  <class 'numpy.ndarray'>


In [71]:
array2d = np.array([[1,2,3],[4,5,6]])
print("Array 2D: \n", array2d)
print("Dimensões do array: ", array2d.shape)
print("Número de dimensões: ", array2d.ndim)
print("Tipo de dados: ", array2d.dtype)
print("Tamanho de cada elemento em bytes: ", array2d.itemsize)
print("Número total de elementos: ", array2d.size)
print("Tipo do objeto: ", type(array2d))    
print("A dimensão do array é: ", len(array2d))

Array 2D: 
 [[1 2 3]
 [4 5 6]]
Dimensões do array:  (2, 3)
Número de dimensões:  2
Tipo de dados:  int64
Tamanho de cada elemento em bytes:  8
Número total de elementos:  6
Tipo do objeto:  <class 'numpy.ndarray'>
A dimensão do array é:  2
